POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MmYyMGY2NjZiNDdiZGExYTZjOGQxZjAiLCJpYXQiOjE2NjAwNTcyNzV9.Tt3mhAg8uriOLqrXHmQz2acPOJZ8R-hTQ1P4zYIvT3s

{
    "title": "Middware",
    "author": "Move",
    "url": "www.pls.com",
    "likes": 70
}