POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxhIiwiaWQiOiI2MmYxNGE1YWFjMDY1ZDhhYTA1OTRhOWMiLCJpYXQiOjE2NjA2NTAzMzF9.08S6zxSLZNQTUe8mlK7xZLH7JvR75gCC33Bh65i-SlI

{
    "title": "Hellalla paisto",
    "author": "Hella",
    "url": "www.noise.zyx",
    "likes": 12
}